#!/usr/bin/env python

import os
from OptsAnalysis import OptsAnalysis

dataDir = r'../data'
for file in os.listdir(dataDir):
    if file.endswith(("xls", "csv")):
        filePath = os.path.join(dataDir, file)
        Opts = OptsAnalysis()
        Opts.BuildFromTS(filePath)
        Opts.PrintExpirationDates()
        expDates = Opts.GetExpirationDates()
        Opts.PlotHistByDate(expDates[0], 'Volume')
        Opts.PlotHistByDate(expDates[0], 'OpenInt')
        Opts.PlotHistByDate(expDates[0], 'Both')
